setup.sh: Move liblz4-devel to lz4 for Arch
error: target not found: liblz4-devel

After checking the official package repos, lz4 provides the required
files.

Ref: https://archlinux.org/packages/core/x86_64/lz4/

Signed-off-by: TH779 <i@779.moe>